### ISSUE TITLE
When trying to run a script, it generates the filepath incorrectly

### ISSUE THREAD

**Issue by jsa34** [jenkinsci/sqlplus-script-runner-plugin#32]
Hello,

I have just updated from SQLPlus Runner 2.0.0 to 2.0.4 and I am unable to run any scripts.

When I debugged, it appears, for some reason to be appending the file name twice to the end of the base URL:

Running script /var/lib/jenkins/jobs/TEST_BUILD/builds/265/SCRIPT.sql on *******/********@*********
java.lang.RuntimeException: Unable to read SQL script [/var/lib/jenkins/jobs/TEST_BUILD/builds/265/SCRIPT.sql/SCRIPT.sql]  !
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:306)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:174)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
ERROR: Unable to read SQL script [/var/lib/jenkins/jobs/TEST_BUILD/builds/265/SCRIPT.sql/SCRIPT.sql]  !

The first part of logging the filepath seems to log the correct location, whereas the stacktrace is appending this file name and extension twice? 

This was working fine in 2.0.0.

Muito obrigado :)

**Comment by jsa34** [comment]
I am using Jenkins on Linux environment, running on host, if that helps :)

**Comment by boaglio** [comment]
Please provide your sqlplus script runner project configuration.

**Comment by jsa34** [comment]
SQL*Plus runner set up in job config:
![image](https://user-images.githubusercontent.com/31512041/49092294-a50e7780-f259-11e8-8a6e-da174902d301.png)

SQL*Plus set up in Jenkins Configuration:
![image](https://user-images.githubusercontent.com/31512041/49092372-cc654480-f259-11e8-9f3e-06702d801a86.png)

**Comment by jsa34** [comment]
The .sql file is located in the workspace of the job

**Comment by boaglio** [comment]
If you hide _File Script_ field I can't help you. Try to turn the _Debug Info_ on and run it again.

**Comment by jsa34** [comment]
Apologies - the original names were sensitive but I have tried to rename for the purposes of testing so I can expose them.

So, I have renamed the .sql file to "TESTING_PREFIX.sql" and ran the job again with debug enabled.

The result looks identical:

![image](https://user-images.githubusercontent.com/31512041/49135624-25c38700-f2df-11e8-8ccc-73a3210d512e.png)

**Comment by boaglio** [comment]
Fixed, please try release 2.0.5 .

**Comment by jsa34** [comment]
Fab - all working :)  Muito obrigado pela ajuda!
