### ISSUE TITLE
ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by rags147** [jenkinsci/sqlplus-script-runner-plugin#37]
I have installed windows on Jenkins. I have unzipped instaclient in C:\Downloads\
I can connect DB server using sqlplus but when I am building my job I am getting this error.

Oracle 

ERROR:
ORA-12541: TNS:no listener

SP2-0751: Unable to connect to Oracle.  Exiting SQL*Plus
Process exited with status 1
--------------------------------------------------------------------------
Exit code: 1
--------------------------------------------------------------------------
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunner.run(SQLPlusRunner.java:446)
	at org.jenkinsci.plugins.sqlplus.script.runner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:174)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
ERROR: Process exited with error
Finished: FAILURE

**Comment by boaglio** [comment]
Please provide:

    Jenkins server Operation System;
    Jenkins version;
    Where SQLPlus Script Runner is running (local machine or slave machine);
    Slave machine Operation System (if applicable);
    Oracle Database version;
    Oracle SQL*Plus version;
    Build log with debug info enabled.

**Comment by boaglio** [comment]
No answer so far, closing issue.
