### ISSUE TITLE
SQL Plus Script runner plugin execution error in Jenkins

### ISSUE THREAD

**Issue by tgunarat** [jenkinsci/sqlplus-script-runner-plugin#5]
Hi Boaglio,
I have configured a Jenkins job with SQL Plus Script runner plugin. 
However, job fails with an error as described below. 

My enviornment details are below:
- Jenkins server Operation System ->  Linux (OS version : 2.6.32-573.8.1.el6.x86_64)
- Jenkins version  - > Jenkins ver. 2.25
- Where SQLPlus Script Runner is running (local machine or slave machine); - > On Slave
- Slave machine Operation System (If applicable); - > Linux
- Oracle Database version; --> Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
- Oracle SQL*Plus version. - > 11.2.0        

My Console Output : 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Building remotely on ho-aifs-dev in workspace /var/lib/jenkins/ho-pg-jenkins-slave/workspace/SQLPLUS_RUNNER
--------------------------------------------------------------------------
Getting ORACLE_HOME...
--------------------------------------------------------------------------
Using custom ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =/opt/oracle/product/11.2.0/client
--------------------------------------------------------------------------
Running defined script on pg/********@QLDDEV.BOM
Temp script:/tmp/temp-script-14871959225503605241968887703821.sql
--------------------------------------------------------------------------
Process exited with status 1
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:249)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:16)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2731)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to ho-aifs-dev(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1433)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:797)
	at hudson.FilePath.act(FilePath.java:985)
	at hudson.FilePath.act(FilePath.java:974)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:401)
ERROR: Process exited with error
Finished: FAILURE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I have tested the database connection from Jenkins server as below. 

[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$ echo $TWO_TASK
QLDDEV.BOM
[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$ echo $ORACLE_HOME
/opt/oracle/product/11.2.0/client
[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$
[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$ echo $TWO_TASK
QLDDEV.BOM
[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$ hostname
ho-aifs-dev.bom.gov.au
[tgunarat@ho-aifs-dev TG_LOCALE_DATA_COMP]$ sqlplus pg@QLDDEV.BOM

SQL*Plus: Release 11.2.0.1.0 Production on Thu Feb 16 08:55:17 2017

Copyright (c) 1982, 2009, Oracle.  All rights reserved.

Enter password:

Connected to:
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production
With the Partitioning, Real Application Clusters, Automatic Storage Management, OLAP,
Data Mining and Real Application Testing options

SQL> select count(*) from FDB.LOCALES_TB;

  COUNT(*)
----------
      7982

SQL>

Jenkins ; SQLPLUS Script Runner Configuration : 
![sql-script-runner-settings-jenkins](https://cloud.githubusercontent.com/assets/25759497/22998757/6105e8d4-f42c-11e6-9d6e-cc66bb47e6f4.png)

The error message doesn't contain any information that I recognise that might be helpful. Your valuable input is much appreciate to solve this issue.

**Comment by boaglio** [comment]
hi  tgunarat, 

I could test here with similar environment , but with Oracle 12.1 , and everything went fine.

You should try:

1. - activate  _Try to detect ORACLE_HOME_  option;
2. - verify the user which is Jenkins is running (maybe it _doesn't_ have the Oracle variables defined);
3. - take a look at your Jenkins log, maybe there is something else we are missing.

**Comment by qkniazi** [comment]
please help: Every thing is good, this plugin is not working for me. 
Started by user Qamar Khan
Building in workspace C:\Users\Qaram Khan\.jenkins\workspace\oracle
--------------------------------------------------------------------------
Getting ORACLE_HOME...
--------------------------------------------------------------------------
Using global ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\OracleClient
--------------------------------------------------------------------------
Running defined script on qkhan/********@Dev
Temp script:C:\Users\QARAMK~1\AppData\Local\Temp\temp-script-14981609391535808302253493810108.sql
--------------------------------------------------------------------------
Process exited with status -1073741515
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:249)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:16)
	at hudson.FilePath.act(FilePath.java:997)
	at hudson.FilePath.act(FilePath.java:975)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
ERROR: Process exited with error
Finished: FAILURE

**Comment by boaglio** [comment]
I think something is wrong with your script.

**Comment by qkniazi** [comment]
Script is simple, creating table. which is working directly out side Jenkins.

**Comment by qkniazi** [comment]
working for me, I installed oracle client as admin, installed it as default folder structure, set up TNS and ORACLE_HOME, installed oracle script runner pluging  and it is working for oracle 12,11 both.

**Comment by misterwalrus** [comment]
Two years later, and yes, it is working for me too.  Only needed ORACLE_HOME to make it work. If I specify SQLPLUS path and/or TNS_ADMIN, it fails complaining about missing TNSNAMES.ORA

**Comment by amitydevops** [comment]
Hi there, did anyone of you tried to run script to the slave server as a sysdba ? Please advise.

When I am running to the slave outside of the Jenkins -- then it is running fine -

export ORACLE_SID=ORCLCDB; sqlplus / as sysdba @/home/oracle/scripts/sql/dbcomps.sql

SQL*Plus: Release 19.0.0.0.0 - Production on Thu Jul 30 10:30:10 2020
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.


Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0


COMP_ID    COMP_NAME                      VERSION    STATUS
---------- ------------------------------ ---------- --------
CATALOG    Oracle Database Catalog Views  19.0.0.0.0 VALID
CATPROC    Oracle Database Packages and T 19.0.0.0.0 VALID

Now in Jenkins --- 
    pipeline {
    agent { label 'slave' }
    stages {
            stage ('invalidobjects') {
             steps {
                echo 'Invalid objects'           
                sh script: "export ORACLE_SID=ORCLCDB; export ORACLE_HOME=/opt/oracle/product/19c/dbhome_1; export PATH=$PATH:$ORACLE_HOME/bin; sqlplus / as sysdba @/home/oracle/scripts/sql/dbcomps.sql"   
             }
            }
        }
    }


Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0


COMP_ID    COMP_NAME                      VERSION    STATUS
---------- ------------------------------ ---------- --------
CATALOG    Oracle Database Catalog Views  19.0.0.0.0 VALID
CATPROC    Oracle Database Packages and T 19.0.0.0.0 VALID

Inside Jenkins:

    pipeline {
    agent { label 'slave' }
    stages {
            stage ('invalidobjects') {
             steps {
                echo 'Invalid objects'           
                sh script: "export ORACLE_SID=ORCLCDB; sqlplus / as sysdba @/home/oracle/scripts/sql/dbcomps.sql"   
             }
            }
        }
    }

Invalid objects
[Pipeline] sh
+ export ORACLE_SID=ORCLCDB
+ ORACLE_SID=ORCLCDB
+ sqlplus / as sysdba @/home/oracle/scripts/sql/dbcomps.sql
/home/slavejenkins/workspace/testdba@tmp/durable-404fe327/script.sh: line 1: sqlplus: command not found
[Pipeline] }

If I pass ORACLE_HOME then getting below message - 
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: ORACLE_HOME for class: WorkflowScript

Thank you.
