### ISSUE TITLE
sqlplus-script-runner-plugin 

### ISSUE THREAD

**Issue by qkniazi** [jenkinsci/sqlplus-script-runner-plugin#7]
I downloaded this plugin. other hand , I have oracle client installed on my computer. ORACLE_HOME environment variable is defined. I am not able to run the dml or ddl. getting this output

Building in workspace C:\Users\Qaram Khan\.jenkins\workspace\oracle
--------------------------------------------------------------------------
Getting ORACLE_HOME...
--------------------------------------------------------------------------
Using global ORACLE_HOME
--------------------------------------------------------------------------
Using ORACLE_HOME =C:\OracleClient
--------------------------------------------------------------------------
Running defined script on qkhan/********@Dev
Temp script:C:\Users\QARAMK~1\AppData\Local\Temp\temp-script-14981609391535808302253493810108.sql
--------------------------------------------------------------------------
Process exited with status -1073741515
java.lang.RuntimeException: Process exited with error
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:249)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunner.invoke(SQLPlusRunner.java:16)
	at hudson.FilePath.act(FilePath.java:997)
	at hudson.FilePath.act(FilePath.java:975)
	at org.jenkinsci.plugins.sqlplusscriptrunner.SQLPlusRunnerBuilder.perform(SQLPlusRunnerBuilder.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:405)
ERROR: Process exited with error
Finished: FAILURE

**Comment by boaglio** [comment]
I think something is wrong with your script. Try to run it by command line with SQL*Plus.

**Comment by qkniazi** [comment]
code is not incorrect sql script runner but not in jenkins plugin. is it compatible with oracle 11 g ?

Sent from my iPhone

On Jun 24, 2017, at 2:49 PM, Fernando Boaglio <notifications@github.com<mailto:notifications@github.com>> wrote:


I think something is wrong with your script. Try to run it by command line with SQL*Plus.

**Comment by boaglio** [comment]
Please inform:

-     Jenkins server Operation System;
-     Jenkins version ;
-     Where SQLPlus Script Runner is running (local machine or slave machine);
-     Slave machine Operation System (if applicable);
-     Oracle Database version;
-     Oracle SQL*Plus version;
-     link do download your SQL*Plus version.

**Comment by qkniazi** [comment]
windows 10 pro local Jenkins
database oracle 11g 
sqlplus script runner in local 
sql plus version 12.1.0.2.0 
downloaded from oracle website

**Comment by qkniazi** [comment]
@boaglio 
![jenkinserror](https://user-images.githubusercontent.com/19601229/27925961-48262250-624c-11e7-9599-e6d16c5ffba7.JPG)
![database](https://user-images.githubusercontent.com/19601229/27925974-527ca710-624c-11e7-9c70-a7d0560f28c6.JPG)
